spring:
  application:
    name: investor
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
