version: '3.3'

services:
  postgres:
    image: postgres
    container_name: investor_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - investor_network
    ports:
      - 5432:5432

networks:
  investor_network:


